os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

install:
  - pip install --user conan
  - pip show conan
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir build && cd build/
  - conan install .. --build missing
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --parallel 2
  - ctest --parallel 2
  - ./bin/hello
