os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build/
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --parallel 2
  - ctest --parallel 2
  - ./hello
